camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 10000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
  subscriptions:
    scoreProvider: # topic name of the External Service Task
      variable-names: [] # our business logic doesn't require any variables, so don't fetch them
      process-definition-key: loan_process # only filter for External Tasks with this process definition key
    loanGranter:
      variable-names: customerId, creditScore # only fetch these two variables
      process-definition-key: loan_process

logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application